credo-ai/credoai_lens

.github/workflows/test.yml
credoai/tests/test_version.py
scripts/test-cov-html.sh
scripts/test.sh

Add test scripts and basic workflow.

chore(tests): add test scripts and workflows

---

README.md
credoai/assessment/assessments.py
credoai/assessment/credo_assessment.py
credoai/data/__init__.py
credoai/lens.py
docs/notebooks/lens_customization.ipynb
docs/notebooks/quickstart.ipynb

Fixes an issue where `getattr` caused an error when the attribute wasn't present.
Also added some documentation and remove superfluous extra parameters from FairnessBase Assessment

updated documentation, fixed binary classification error

---

credoai/modules/dataset_assessments/dataset_base.py
requirements-extras.txt

Segmentation fault seemed to be because of installing pip-installable xgboost. Xgboost is too finicky to install to make it amere requirement (for pip). Revisit with conda.

removed xgboost as requirement

---

credoai/utils/credo_api_utils.py

fix for metrics not assigned to models

---

credoai/lens.py

Quick fix for metrics coming from alignment

quick fix for FairnessBase metrics

---

tests/test_lens.py

Test for lens.Lens

---

docs/notebooks/quickstart.ipynb

fixed typo in quickstart

---

credoai/modules/dataset_modules/dataset_base.py

Added proxy assessment in feature space

added proxy assess in feature space

---

README.md
docs/setup.rst

> Description here
> Fix [#1]()

updated installation docs

---

credoai/reporting/fairness_binaryclassification.py

Fixed axis label setting in FairnessReporter._style_barplot

fixed ylabel setting

---

docs/notebooks/lens_demos/binaryclassification.ipynb

fixed import

---

credoai/reporting/dataset_fairness.py

Refers to [DS-399](https://credo-ai.atlassian.net/browse/DS-399?atlOrigin=eyJpIjoiNDMzODE1MmJhZTY0NGVlNTkwNzgwNzIwNWU3M2QzNWYiLCJwIjoiaiJ9)

change check condition for empty standardized group diffs

---

credoai/integration.py
credoai/lens.py
credoai/utils/common.py
credoai/utils/credo_api_utils.py

Don't serialize output when downloading assessment results to file.

removed unnecessary values when downloading json

---

credoai/artifacts.py
credoai/integration.py
credoai/lens.py
credoai/modules/dataset_modules/dataset_fairness.py

Addresses DS-428, and other small issues.

fix: added better error reporting, fixed error with dataset fairness

---

credoai/assessment/credo_assessment.py
credoai/integration.py
credoai/lens.py
credoai/modules/dataset_modules/dataset_profiling.py

Fixed issue with export introduced by empty prepared results. Now prepared results can be empty!

fixed bug with dataset profiler and empty prepared results

---

credoai/assessment/utils.py
credoai/lens.py

Fixed issue with assessments based on model alone

fixed bug where lens wasn't dealing with assessments that don't use data

---

credoai/artifacts.py
credoai/integration.py
credoai/utils/credo_api_utils.py

This adds the ability to register a validation dataset to a model in a use case.

Register validation datasets to model-use-case

---

credoai/metrics/credoai_metrics.py
credoai/metrics/metric_constants.py
docs/metrics.rst
requirements.txt

* Adds Kolmogorov-Smirnov test as a distribution comparison metric for regression
* Add the missing scipy to the requirements
* Updates metrics.rst

Regression features

---

credoai/assessment/assessments.py
credoai/assessment/credo_assessment.py

This adds training data to CredoAssessment to accommodate for modules that require that for their assessments (e.g., Privacy)

Added training data to CredoAssessment

---

credoai/assessment/assessments.py
credoai/lens.py
credoai/metrics/metrics.py

Removed duplicate metrics from performance and fairness when used together (disaggregated metrics)

removed duplicatations when performance and fairness are used together

---

credoai/artifacts.py
credoai/integration.py
credoai/lens.py

changed assess_at at back

---

credoai/reporting/model_fairness.py

Reporting was failing for regression assessment. This fixes the issue via upgrading regression reporter to work with multiple disaggregators.

fixed reporting for regression

---

credoai/lens.py
credoai/modules/model_modules/fairness_base.py
credoai/modules/model_modules/performance_base.py

Some small fixes to improve error understanding

added additional checks to make errors more understandable

---

credoai/artifacts.py
credoai/integration.py
credoai/lens.py

fix(): use utctime for assessed_at (AAA-1357)

---

credoai/artifacts.py
credoai/assessment/utils.py
credoai/integration.py
credoai/lens.py
credoai/metrics/metrics.py
credoai/modules/model_modules/fairness_base.py
credoai/modules/model_modules/nlp_generator.py
credoai/modules/model_modules/performance_base.py
credoai/utils/__init__.py
credoai/utils/common.py
credoai/utils/credo_api.py
credoai/utils/logging.py
docs/conf.py
docs/notebooks/lens_demos/dataset_profiling.ipynb
requirements-extras.txt

_register_model returns status string. 
- `registered` when successfully registered
- `already_registered` when it is already registered
- `registration_failed`  when API fails
- `use_case_id_not_exist` when use_case_id does not exist
Related slack message : https://credoai.slack.com/archives/C021XG5DZRA/p1662130604086429

feat(): _register_model returns status string

---

credoai/artifacts/model/base_model.py
credoai/artifacts/model/classification_model.py

Trying to deal with issue with predict_proba leading to possible issues in binary case.

update predict_proba when binary classification in sklearn framework

---

docs/notebooks/governance_integration.ipynb

- Section Governance in 5 minuts

Fixed notebook error

---

credoai/artifacts/data/base_data.py
credoai/artifacts/data/tabular_data.py

For some reason validation and processing was removed during some previous PR. adding back in.

fixed processing and validation that were somehow lost

---

credoai/evaluators/fairness.py

Quick bug fixes after last merge

fixed bugs with fairness after merging

---

credoai/evidence/evidence.py

> Description here
> Fix [#1]()

quick import fix

---

docs/metrics.rst

* Corrected script for listing metrics
* Added privacy and security metrics
* Added RAI dimensions

Updated metrics doc

---

credoai/evaluators/utils/utils.py

Fixing function to find all evaluator subclasses

---

credoai/lens/lens.py
docs/notebooks/platform_integration.ipynb

Change default parameter from False to True for the Lens.send_to_governance function.
Also update language in platform_integration notebook
- [X ] Bug fix (fixes an issue) DSP-311 (private to Credo)

Change send_to_governance function to default to overwrite existing evidence

---

tests/test_lens.py

Add `lens.send_to_governance()` to all test cases.

Add calls to send_to_governance to all test cases

---

docs/index.rst

> Description here
> Fix [#1]()

Grammar change in first paragraph of docs

---

credoai/datasets/_fetch_credit_model.py

allowed training data to be pulled for fetch_credit_data

---

credoai/artifacts/model/base_model.py
credoai/lens/lens.py

Fixed tags being passed to `connect` correctly and set default empty tags.

fixed tag bugs

---

docs/requirements.txt

Added connect to docs
Lack of connect was causing docs to fail

add connect to doc requirements

---

credoai/lens/lens.py

Modify `print_results()` function to reflect new format of return object from `get_results()`. Metadata and results are separate per evaluator per assessment.
Fixes #275 
None
- See #272 
- N/A
- No
- N/A

Refactor print_results() function

---

credoai/artifacts/data/base_data.py
credoai/artifacts/data/tabular_data.py
credoai/utils/common.py

`TabularData` wasn't properly validating pre/post processing. This PR fixes that. 
Also added basic name validation.
* Should we just require the input to be a dataframe?

update validation functions

---

.github/workflows/test-reports.yml

My first "fix" was a typo.  Should have been secrets instead of env.
Also, trying to make the pip cache work.

Fix secrets and hopefully pip cache

---

docs/index.rst

Added new directions at the beginning to clearly indicate how a new user should approach Lens. [Link to docs](https://credoai-lens.readthedocs.io/en/docs-update/)

updated index to direct new customers

---

.github/workflows/test.yml

Change test.yml to make failing tests trigger workflow failure
https://credoai.slack.com/archives/C021XG5DZRA/p1671758449743539?thread_ts=1671756399.776979&cid=C021XG5DZRA
N/A

add command to pipe results to mark failure

---

credoai/artifacts/data/base_data.py
credoai/artifacts/data/tabular_data.py
credoai/evaluators/data_profiler.py
credoai/utils/common.py
tests/fixtures/datasets.py

Minor change to include sensitive features in data profiler. Also added metadata about which features were which.
Main point of this PR is to add the sensitive feature tables.

added sensitive features to data profiler

---

credoai/evaluators/ranking_fairness.py
credoai/modules/metrics_credoai.py

Refactored Ranking Fairness evaluators
* Generic metrics moved to `metrics_credoai.py`
* FINS metrics refactored to helper function
* Reformatted some codes and documentations

Ranking fairness refactoring

---

credoai/evaluators/equity.py
credoai/modules/metrics_credoai.py
requirements.txt
tests/fixtures/lens_inits.py

Fixed a couple of failing tests
- Updated equity to call on the new StatisticTestContainer
- Fixed a couple of broken tests
Dependent on merging of [credoai-connect PR #17](https://github.com/credo-ai/credoai_connect/pull/17). 
[Chi-squares test statistic with p value](https://credo-ai.atlassian.net/browse/DSP-359?atlOrigin=eyJpIjoiYzE0NTVlMzQ5NjRjNDVhOWJhMTQ2YjI1YTMwNmQwNDkiLCJwIjoiaiJ9
)

Updated equity to leverage statistic test evidence

---

requirements-dev.txt
requirements.txt

Updated requirements. Added connect develop branch to develop requirements.

updated requirements

---

credoai/evaluators/evaluator.py

All evidence should have a "source" specified. CredoAI Lens evidence should be labeled as coming from "CredoAI_Lens"

added source to all lens outputs

---

credoai/__init__.py
credoai/_version.py
credoai/utils/version_check.py
docs/requirements.txt
requirements-dev.txt
setup.py

Fixed versioning system for package deployment

updated version issues

---

credoai/artifacts/model/classification_model.py

Fixes https://credo-ai.atlassian.net/browse/DSP-391

Only call check_array if predict or predict proba is provided

---

credoai/lens/lens_validation.py

Fixes https://credo-ai.atlassian.net/jira/software/c/projects/DSP/boards/29?modal=detail&selectedIssue=DSP-395

Only run validation if input data is actually provided

---

credoai/utils/version_check.py

Correcting version import

---

credoai/evaluators/fairness.py

- Leveraged confusion matrix function in Performance to create a disaggregated version in Fairness.

Added confusion matrix for fairness evaluator

---

credoai/__init__.py
docs/notebooks/quickstart.ipynb

- Updated documentation link in notebook to reflect change in folder structure
- Fixed reference to version in `credoai.__init__.py` file
https://credo-ai.atlassian.net/browse/DSP-400?atlOrigin=eyJpIjoiOTgwN2Q1ZTZlMGE0NDQ1YTkwNTI2NGFmNjg0YWI3YTUiLCJwIjoiaiJ9

Fix/documentation link + version

---

credoai/artifacts/model/classification_model.py
credoai/evaluators/fairness.py
credoai/evaluators/performance.py

Removed second passage of `message` in logger warning message.
Remove requirement that `data.X` be supplied for Performance and Fairness evaluators
Update `model.type` assignment for DummyClassifier and Keras classifiers.
Various slack messages...

Multiple Validation Fixes for DummyClassifiers

---

docs/notebooks/lens_faq.ipynb
docs/notebooks/quickstart.ipynb

Platform integration notebook was still known as `governance_integration` in varous places.

Fixing broken links to platform integration notebook

---

README.md
credoai/modules/metric_utils.py
docs/conf.py
docs/index.rst
docs/notebooks/lens_faq.ipynb
docs/notebooks/quickstart.ipynb
docs/requirements.txt

Making changes to improve initial onboarding and fix minor `list_metrics` bug. Documentation can be reviewed [here](https://credoai-lens.readthedocs.io/en/dsp-474-make-documentation-changes-based-on-oleg-input/index.html)
Changes:
* New intro for the main documentation page
* Fixed links in quickstart
* Added better output of results in quickstart
* lens FAQ `list_metrics` shows all metrics

Dsp 474 make documentation changes based on oleg input

---

credoai/evaluators/data_fairness.py
credoai/evaluators/data_profiler.py
credoai/evaluators/deepchecks_credoai.py
credoai/evaluators/equity.py
credoai/evaluators/fairness.py
credoai/evaluators/feature_drift.py
credoai/evaluators/identity_verification.py
credoai/evaluators/model_profiler.py
credoai/evaluators/performance.py
credoai/evaluators/privacy.py
credoai/evaluators/ranking_fairness.py
credoai/evaluators/security.py
credoai/evaluators/shap_credoai.py
credoai/evaluators/survival_fairness.py
docs/notebooks/lens_faq.ipynb
docs/pages/evaluators.rst

More improvements. See example updates evaluator documentation [here](https://credoai-lens.readthedocs.io/en/more_onboarding_improvements/_autosummary/credoai.evaluators.performance.Performance.html#credoai.evaluators.performance.Performance).
Also added this section to [FAQ](https://credoai-lens.readthedocs.io/en/more_onboarding_improvements/notebooks/lens_faq.html#What-evaluators-exist-in-Lens?)

updated evaluator documentation
