credo-ai/credoai_lens

- credoai/modules/model_assessments/fairness_base.py
- credoai/utils/common.py
in get_df(self):
```
if self.y_prob is not None:
y_prob_df = pd.DataFrame(self.y_prob)
y_prob_df.columns = [f'y_prob_{i}' for i in range(y_prob_df.shape[1])]
df = pd.concat([df, y_prob_df], axis=1)
```
something wrong happened:
```
df.shape, y_prob_df.shape, pd.concat([df, y_prob_df], axis=1).shape
((65, 3), (65, 2), (107, 5))
```
maybe the index of df should be dropped:
```
df.shape, y_prob_df.shape, pd.concat([df.reset_index(), y_prob_df], axis=1).shape
((65, 3), (65, 2), (65, 6))
```
- [ x ] Bug fix (fixes an issue)
> Fix [#1]()
> fix for create_reports()

- docs/notebooks/module_demos/fairness_nlp.ipynb
- docs/tutorials.rst
Reformatted the headers in the tutorials rst file and embedding demo notebook. This fixes the Nav bar in readthedocs tutorial documentation page being broken issue (Jira DS-332).
> updated header formats for toc fix

- credoai/modules/credo_module.py
- credoai/modules/dataset_modules/dataset_base.py
- credoai/modules/model_modules/fairness_base.py
Updated dataset to return "prepared_results". Implicitly started creating "dataset metric types", which will be rolled into the overall taxonomy of metrics. Prepared results look like this:
Notice the metadata associated with individual metrics. "target" is associated with some, but not others. I think the "target" is confusing currently. We don't have an equivalent idea for the fairness base module. But I think it's fine to not deal for now
> updated dataset preparation to work

- credoai/reporting/reports.py
- docs/conf.py
- requirements.txt
Using Quickstart notebook, Restart & Run all causes below error then kernel dies. Root cause is non-rentrant default asyncio, which can be fixed by applying the nest_asyncio library.
Background: https://bugs.python.org/issue22239
Traceback (most recent call last):
File "/Users/eli/miniconda3/envs/dogfood/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/eli/miniconda3/envs/dogfood/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Users/eli/miniconda3/envs/dogfood/lib/python3.9/site-packages/ipykernel_launcher.py", line 16, in <module>
app.launch_new_instance()
File "/Users/eli/miniconda3/envs/dogfood/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance …
> Fix async notebook execution by using reentrant asyncio

- credoai/lens.py
Reporters were being overwritten when the same assessment was run twice (e.g., on training and validation data). This fixes it.
> fixed reporter overwriting bug

- credoai/lens.py
- credoai/reporting/dataset_fairness.py
A small PR that add percentage labels to data balance plot.
Runningun [dataset_assessment.ipynb](https://github.com/credo-ai/credoai_lens/blob/develop/docs/notebooks/lens_demos/dataset_assessment.ipynb):
> Added percentage labels to data balance plot

- credoai/modules/model_modules/fairness_base.py
- credoai/modules/model_modules/performance_base.py
This small PR addresses cases where Lens does not find any matches for a user-specified metric name.
> Metric search exception handling

- credoai/assessment/assessments.py
- credoai/modules/__init__.py
- credoai/modules/model_modules/computational_efficiency.py
- credoai/modules/model_modules/fairness_base.py
- credoai/modules/model_modules/performance_base.py
- tests/test_lens.py
Small module that calculates the average time of inference for a batch of 1000. Separated into a separate module (rather than performance) because inference _has_ to happen within the module.
This will connect with new risk issues introduced in this [fast-follow PR](https://github.com/credo-ai/rai-service/pull/36)
Example:
> added basic computational efficiency inference module

- .github/workflows/test.yml
We want to store the pytest-coverage.txt file as an artifact on all test runs.
> Always upload the pytest coverage log as an artifact

- requirements.txt
pandas-profiling 3.2.0 uses MarkupSafe 2.1.1, this causes error while loading lib. So fix the version to 3.1.0, which uses MarkupSafe 2.0.1
Related to https://github.com/credo-ai/credoai_lens/issues/141
> fix pandas_profiling version to 3.1.0

- credoai/governance/governance.py
- credoai/utils/common.py
- tests/credoai/governance/test_governance.py
`gov.export(filename)` saves assessment to the filename. 
The format is json api. So the UI app just need to pass this data to the API server. 
It also saves Lens version in meta. So that UI app and API server verifies that it is generated from Lens.
> feat(): export  assessment to file

- credoai/governance/credo_api.py
- credoai/governance/governance.py
- docs/notebooks/governance.ipynb
Now API server accepts assessment_plan_url without policy pack key, PR : https://github.com/credo-ai/credo-backend/pull/799
It will return the URL with the first registered policy pack.
```
gov.register(use_case_name=="Fraud Detector")
```
It is useful when the use case uses only one policy pack.
> Can register without policy_pack_key

- requirements.txt
Updated pandas-profiling version in the requirements file
This fixes `from pandas.core.base import DataError` error thrown in pandas-profiling module during `import credoai.lens`
We can also consider `pandas_profiling>=3.3.0` but this relaxation has caused issues like [here](https://github.com/credo-ai/credoai_lens/issues/141) in the past.
> Updated pandas-profiling version

- credoai/evaluators/privacy.py
- tests/conftest.py
- tests/test_lens.py
- Removed new syntax for dictionary join
- Fixed minor logic error in privacy package
- Added credit dataset to test, needed for AttributeInferenceBaseline testing.
> Make privacy python3.8 compatible

- credoai/lens/lens.py
Validation of arguments in Lens didn't allow for assessment_data being optional.
> Assessment data validation fix

- credoai/__init__.py
- credoai/evidence/evidence.py
DataProfiler was using data `DataProfilerEvidence` with `type="profiler"` this doesn't match current platform.
--> Changed type to "dataset_profiler"
> DataProfiler evidence fix + version update

- credoai/modules/credoai_metrics.py
For some applications, ROC curve appears cut off when plotted. This is due to insufficiently granular interpolation of outputs of sklearn's `roc_curve` function.
Modified quantization level in interpolator helper functions to be set as a function of 1) number of thresholds returned by `roc_curve` function (or pr curve or det curve) and 2) difference between max and min threshold.
- [ X] Bug fix (fixes an issue)
> modify quantization of roc and pr curve interpolation helpers to ensure adequately dense interpolation

- credoai/lens/lens.py
Deep copy pipeline steps for all evaluators added to Lens as part of pipeline list passed to the Lens constructor (rather than added individually through `add()`
- [ X] Bug fix (fixes an issue)
#238
> 238 shallow copy issue creating lens objects with the same pipeline object causes the latter object to overwrite the results from the former

- credoai/artifacts/model/classification_model.py
- credoai/utils/model_utils.py
See https://github.com/credo-ai/credoai_lens/pull/185 
Fixes same issue but now enables XGBoostClassifier (which has a framework string of "xgboost.sklearn" and was not previously having its `predict_proba()` functionality updated when wrapped in a Credo `ClassificationModel`
Specifically: modify `get_model_info()` utility function to keep framework as full string (not split, not indexed). Modify `update_functionality()` in `ClassificationModel` class to check for `"sklearn"` in the `framework` variable rather than strict equality.
- [ X] Bug fix (fixes an issue)
> Modify get_model_info and update_functionality so that model frameworks are full string. Enables use of XGBoost within Credo Models

- credoai/lens/lens.py
Modify Lens class to support optional use of joblib.
Lens constructor now takes as optional input an `n_jobs` parameter. Parameter is used in the `Lens.run()` function to parallelize running of evaluators.
Results returned by each evaluator's `evaluate` function are evaluators, rather than pipeline steps. Therefore, results must be stored in an intermediate list and then re-matched with metadata in `self.pipeline`
- [ X] New feature (adds functionality)
> Add joblib support to Lens to enable running evaluators in parallel

- tests/test_lens.py
Add call to `lens.get_evidence()` as a unit test for each evaluator in the test_lens suite. Where possible (i.e. in class-based tests), `get_evidence` is it's own unit test. In some cases (non-class-based tests), `get_evidence` is added as an additional assert after `get_results()`
- [ X ] New feature (adds functionality)
> Modify test_lens to call get_evidence for each test

- credoai/__init__.py
- credoai/utils/__init__.py
- credoai/utils/version_check.py
Changes credoai-lens's version to be based on installed wheel, rather than hardcoded string.
Adds functionality to check latest version of package on PyPI. If installed version is not identical to latest version, Lens's logger will throw a warning instructing the user to update.
- [X ] New feature (adds functionality)
> Add functionality to check version of Lens on import

- credoai/lens/lens.py
#263 fix was still causing issues. 
Governance `set_artifacts()` expects strings, not model or data objects: https://github.com/credo-ai/credoai_connect/blob/develop/connect/governance/governance.py#L278
Evidence was showing up in Platform as an object rather than a name
Items 2 and 3 in the screenshot are same evidence. First is w/object passed to `set_artifacts()`, second with name passed (i.e. with the changes in this PR applied).
> Governance set_artifacts expects names, not objects

- .github/workflows/test.yml
- credoai/lens/pipeline_creator.py
- tests/conftest.py
- tests/test_integration.py
Enabled these environment variables for use in CI jobs.
`CREDOAI_LENS_CONFIG_JSON_B64` - Base64 encoded json
Example:
```
export CREDOAI_LENS_CONFIG_JSON_B64=$(cat <<EOF
{
"api_key": "secret",
"tenant": "credoai",
"api_server": "https://api.credo.ai"
}
EOF
)
```
`CREDOAI_LENS_PLAN_URL` - regular string
> Adds support for passing config and assessment plan URL for CI

- credoai/evaluators/performance.py
Converts the confusion matrix table from a square table (with predicted labels as columns and true labels as rows) to a long format looking like this:
> reformated confusion matrix

- .github/workflows/test-reports.yml
The env variables that are needed to run the integration test were dropped during some file shuffling.  This should fix things.
> fix(): restore env variables that were removed during the cleanup

- credoai/artifacts/model/classification_model.py
- credoai/lens/lens_validation.py
For DummyClassifier: change prediction functions to be lambdas so that the functions don't refer to attributes that don't exist if the user has not provided one of predict/predict_proba
For DummyClassifier & DummyRegressor: change validation to compare ALL outputs of predict/predict proba to y. Other models jsut predict on a sample for latency reasons...Better to check full output for dummys
https://credoai.slack.com/archives/C04612H3P7T/p1673996354009329
> Fixing validation for Dummy models which don't specify a prediction function

- credoai/modules/constants_metrics.py
- credoai/modules/metrics_credoai.py
- docs/autogeneration/pages/metrics.py
- docs/autogeneration/pages/metrics_info_manual.json
- docs/pages/metrics.rst
- tests/test_regression.py
Duplicated ks_score metric for binary classifiers.
It's not super clean, but creating a single function incurs in other issues with the `metric_frame`.
I created aliases for the names:
```
"target_ks_statistic": ["ks_score_regression", "ks_score"],
"ks_score_binary": ["ks_score"]
```
so existing notebooks shouldn't break, but you can refer to the metric using `ks_score` and it automatically select the correct one.
@amrasekh if you have notebooks running ks_score for regression models, please test to make sure they aren't broken.
> Added support for ks score to classification models

- credoai/artifacts/data/base_data.py
- credoai/artifacts/model/classification_model.py
- credoai/evaluators/fairness.py
Change default value for `y_prob` in fairness.py to `None` from tuple.
Change variance checking in tabular data with sensitive features to simply check to see that there is more than 1 value for each sensitive group for the outcome. Addresses issue with string-type outcomes (which have no std function)
https://credo-ai.atlassian.net/browse/DSP-464
https://credo-ai.atlassian.net/browse/DSP-465
N/A
> Quick fixes for bugs relating to validation of string-containing DFs and default value for empty y_prob

- credoai/artifacts/model/classification_model.py
Changed the way model type is determined:
- if only 2 classes are present, in order for it to be considered binary classification, they must be in the form [0, 1]
Otherwise the model is considered multiclass and a warning message is issued.
> Dsp 467 update multi class definition and criteria in lens
